"""Added is_safe column to worlds

Revision ID: 0c31afdd0aac
Revises: 7ec95167f6de
Create Date: 2021-03-18 15:39:53.946431

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = '0c31afdd0aac'
down_revision = '7ec95167f6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('is_safe', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'is_safe')
    # ### end Alembic commands ###
