"""add avatar and timestamp columns

Revision ID: 131ac4979519
Revises: 78624ea61cdb
Create Date: 2023-06-21 16:58:33.775964

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '131ac4979519'
down_revision = '78624ea61cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bans', sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('bans', sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'updated_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'avatars', ['avatar_id'], ['id'])
    op.add_column('worlds', sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('worlds', sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'updated_timestamp')
    op.drop_column('worlds', 'created_timestamp')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'avatar_id')
    op.drop_column('bans', 'updated_timestamp')
    op.drop_column('bans', 'created_timestamp')
    op.drop_table('avatars')
    # ### end Alembic commands ###
