"""web_service migration

Revision ID: 283cbb3e3b4d
Revises: accb33fc9aee
Create Date: 2024-10-07 00:09:43.679682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '283cbb3e3b4d'
down_revision: Union[str, None] = 'accb33fc9aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Easy', 'Medium', 'Hard', 'Extreme', name='stamprank').create(op.get_bind())
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('power_id', sa.SmallInteger(), nullable=False),
    sa.Column('element', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('sort', sa.SmallInteger(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('bait', sa.Boolean(), nullable=False),
    sa.Column('max_quantity', sa.SmallInteger(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_options',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('games',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('stamp_set_id', sa.Integer(), nullable=False),
    sa.Column('show_player_in_room', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('igloo_floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('igloos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('layer', sa.SmallInteger(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('bait', sa.Boolean(), nullable=False),
    sa.Column('epf', sa.Boolean(), nullable=False),
    sa.Column('tour', sa.Boolean(), nullable=False),
    sa.Column('treasure', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polaroids_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('display', sa.String(length=256), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('in_catalog', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puffle_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('play_external', sa.String(length=256), nullable=False),
    sa.Column('consumption', sa.String(length=256), nullable=False),
    sa.Column('class_name', sa.String(length=256), nullable=False),
    sa.Column('root_item_id', sa.Integer(), nullable=False),
    sa.Column('only_purchase', sa.Boolean(), nullable=False),
    sa.Column('effect_food', sa.SmallInteger(), nullable=False),
    sa.Column('effect_rest', sa.SmallInteger(), nullable=False),
    sa.Column('effect_play', sa.SmallInteger(), nullable=False),
    sa.Column('effect_clean', sa.SmallInteger(), nullable=False),
    sa.Column('reaction', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puffles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['puffles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stamps_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['stamps_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_messages',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('igloo_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igloo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['igloo_id'], ['igloos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('stamp_id', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polaroids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('stamp_count', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('earnable_by_client', sa.Boolean(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['polaroids_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('jump_enabled', sa.Boolean(), nullable=False),
    sa.Column('required_item', sa.Integer(), nullable=True),
    sa.Column('safe_start_x', sa.Integer(), nullable=False),
    sa.Column('safe_end_x', sa.Integer(), nullable=False),
    sa.Column('safe_start_y', sa.Integer(), nullable=False),
    sa.Column('safe_end_y', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['required_item'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stamps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.Column('rank', postgresql.ENUM('Easy', 'Medium', 'Hard', 'Extreme', name='stamprank', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['stamps_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('mascot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'mascots', ['mascot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mascot_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'mascot_id')
    op.drop_table('stamps', if_exists=True)
    op.drop_table('rooms', if_exists=True)
    op.drop_table('polaroids', if_exists=True)
    op.drop_table('mascots', if_exists=True)
    op.drop_table('igloo_locations', if_exists=True)
    op.drop_table('tour_messages', if_exists=True)
    op.drop_table('stamps_collection', if_exists=True)
    op.drop_table('puffles', if_exists=True)
    op.drop_table('puffle_items', if_exists=True)
    op.drop_table('postcards', if_exists=True)
    op.drop_table('polaroids_collection', if_exists=True)
    op.drop_table('jokes', if_exists=True)
    op.drop_table('items', if_exists=True)
    op.drop_table('igloos', if_exists=True)
    op.drop_table('igloo_floors', if_exists=True)
    op.drop_table('games', if_exists=True)
    op.drop_table('game_options', if_exists=True)
    op.drop_table('furniture', if_exists=True)
    op.drop_table('cards', if_exists=True)
    sa.Enum('Easy', 'Medium', 'Hard', 'Extreme', name='stamprank').drop(op.get_bind())
    # ### end Alembic commands ###
