"""Added ban

Revision ID: 3b4299d686e9
Revises: 0c31afdd0aac
Create Date: 2021-03-19 20:33:30.576021

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = '3b4299d686e9'
down_revision = '0c31afdd0aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ban_type', sa.Enum('MANUAL_BAN', 'AUTO_BAN', 'CHEATING_BAN', name='bantype'), nullable=False),
    sa.Column('ban_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ban_expire', sa.DateTime(), nullable=False),
    sa.Column('ban_user', sa.Integer(), nullable=False),
    sa.Column('ban_comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('user_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('user_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_updated')
    op.drop_column('users', 'user_created')
    op.drop_table('bans')
    # ### end Alembic commands ###
