"""Base migration

Revision ID: 550cd8606bd1
Revises: 
Create Date: 2024-09-07 23:58:25.280870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '550cd8606bd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MANUAL_BAN', 'AUTO_BAN', 'CHEATING_BAN', name='bantype').create(op.get_bind())
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('head', sa.Integer(), nullable=False),
    sa.Column('face', sa.Integer(), nullable=False),
    sa.Column('neck', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('hand', sa.Integer(), nullable=False),
    sa.Column('feet', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=False),
    sa.Column('transformation', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('access_key', sa.String(length=32), nullable=False),
    sa.Column('grant_scopes', postgresql.ARRAY(sa.String(length=30)), server_default='{}', nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=30)), server_default='{}', nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String(length=30)), server_default='{}', nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ban_type', postgresql.ENUM('MANUAL_BAN', 'AUTO_BAN', 'CHEATING_BAN', name='bantype', create_type=False), nullable=False),
    sa.Column('ban_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ban_expire', sa.DateTime(), nullable=False),
    sa.Column('ban_user', sa.Integer(), nullable=False),
    sa.Column('ban_comment', sa.String(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bans')
    op.drop_table('users')
    op.drop_table('worlds')
    op.drop_table('avatars')
    sa.Enum('MANUAL_BAN', 'AUTO_BAN', 'CHEATING_BAN', name='bantype').drop(op.get_bind())
    # ### end Alembic commands ###
