"""added grant_scopes column

Revision ID: 7ec95167f6de
Revises: 978186290230
Create Date: 2020-11-04 00:00:04.222489

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = "7ec95167f6de"
down_revision = "978186290230"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worlds",
        sa.Column(
            "grant_scopes",
            sa.ARRAY(sa.String(length=30)),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worlds", "grant_scopes")
    # ### end Alembic commands ###
