"""make scores an array column

Revision ID: 8d2ffe323281
Revises: 93ef17250727
Create Date: 2020-10-31 20:11:20.879206

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = '8d2ffe323281'
down_revision = '93ef17250727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scopes')
    op.drop_table('scopes')
    op.add_column('users', sa.Column('scopes', sa.ARRAY(sa.String(length=30)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scopes')
    op.create_table('scopes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('scopes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tag', citext.CIText(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['scopes.id'], name='scopes_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scopes_pkey'),
    sa.UniqueConstraint('tag', name='scopes_tag_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_scopes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], name='user_scopes_scope_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_scopes_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
