"""added world table

Revision ID: 978186290230
Revises: 8d2ffe323281
Create Date: 2020-11-01 12:05:43.154200

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = "978186290230"
down_revision = "8d2ffe323281"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worlds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("lang", sa.Integer(), nullable=False),
        sa.Column("access_key", sa.String(length=32), nullable=False),
        sa.Column(
            "scopes",
            sa.ARRAY(sa.String(length=30)),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_key"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worlds")
    # ### end Alembic commands ###
