"""Add url column to world table

Revision ID: accb33fc9aee
Revises: 43fd37ea465e
Create Date: 2024-09-28 12:22:44.333476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'accb33fc9aee'
down_revision: Union[str, None] = '43fd37ea465e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'url')
    # ### end Alembic commands ###
