"""Make parent_ids & gift_id nullable

Revision ID: baf1add0a253
Revises: f65e128467b5
Create Date: 2024-10-20 17:54:55.357156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'baf1add0a253'
down_revision: Union[str, None] = 'f65e128467b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mascots', 'gift_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mascots', 'gift_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
