"""Move 'earnable_by_client' to stamps

Revision ID: bb203b95fe89
Revises: baf1add0a253
Create Date: 2024-10-21 22:04:40.844092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'bb203b95fe89'
down_revision: Union[str, None] = 'baf1add0a253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polaroids', 'earnable_by_client')
    op.add_column('stamps', sa.Column('earnable_by_client', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stamps', 'earnable_by_client')
    op.add_column('polaroids', sa.Column('earnable_by_client', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
