"""add spawn column to rooms table

Revision ID: f65e128467b5
Revises: 283cbb3e3b4d
Create Date: 2024-10-07 01:22:14.371320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f65e128467b5'
down_revision: Union[str, None] = '283cbb3e3b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('spawn', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'spawn')
    # ### end Alembic commands ###
